[package]
name = "fshuf"
version = "0.1.0"
authors = [ "k4rakara <jack@insertdomain.name>" ]
edition = "2018"

[dependencies]
clml_rs = { git = "https://github.com/K4rakara/clml-rs" }
rand = "0.7.3"
regex = "1.5.5"
