#!/usr/bin/bash

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width          0
bspc config normal_border_color   "#222222"
bspc config active_border_color   "#222222"
bspc config focused_border_color  "#222222"
bspc config window_gap            16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a firefoxdeveloperedition:Toolkit state=floating sticky=true
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

